# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gateway_pb2 as gateway__pb2

GRPC_GENERATED_VERSION = '1.72.0rc1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayServiceStub(object):
    """—— service definition —— 

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendIntent = channel.unary_unary(
                '/intentlayer.v2.GatewayService/SendIntent',
                request_serializer=gateway__pb2.SendIntentRequest.SerializeToString,
                response_deserializer=gateway__pb2.SendIntentResponse.FromString,
                _registered_method=True)
        self.StreamIntents = channel.stream_stream(
                '/intentlayer.v2.GatewayService/StreamIntents',
                request_serializer=gateway__pb2.StreamIntentsRequest.SerializeToString,
                response_deserializer=gateway__pb2.StreamIntentsResponse.FromString,
                _registered_method=True)
        self.RegisterDid = channel.unary_unary(
                '/intentlayer.v2.GatewayService/RegisterDid',
                request_serializer=gateway__pb2.RegisterDidRequest.SerializeToString,
                response_deserializer=gateway__pb2.RegisterDidResponse.FromString,
                _registered_method=True)
        self.StreamDids = channel.stream_stream(
                '/intentlayer.v2.GatewayService/StreamDids',
                request_serializer=gateway__pb2.StreamDidsRequest.SerializeToString,
                response_deserializer=gateway__pb2.StreamDidsResponse.FromString,
                _registered_method=True)


class GatewayServiceServicer(object):
    """—— service definition —— 

    """

    def SendIntent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamIntents(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterDid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamDids(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.SendIntent,
                    request_deserializer=gateway__pb2.SendIntentRequest.FromString,
                    response_serializer=gateway__pb2.SendIntentResponse.SerializeToString,
            ),
            'StreamIntents': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamIntents,
                    request_deserializer=gateway__pb2.StreamIntentsRequest.FromString,
                    response_serializer=gateway__pb2.StreamIntentsResponse.SerializeToString,
            ),
            'RegisterDid': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDid,
                    request_deserializer=gateway__pb2.RegisterDidRequest.FromString,
                    response_serializer=gateway__pb2.RegisterDidResponse.SerializeToString,
            ),
            'StreamDids': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamDids,
                    request_deserializer=gateway__pb2.StreamDidsRequest.FromString,
                    response_serializer=gateway__pb2.StreamDidsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'intentlayer.v2.GatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('intentlayer.v2.GatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayService(object):
    """—— service definition —— 

    """

    @staticmethod
    def SendIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intentlayer.v2.GatewayService/SendIntent',
            gateway__pb2.SendIntentRequest.SerializeToString,
            gateway__pb2.SendIntentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamIntents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/intentlayer.v2.GatewayService/StreamIntents',
            gateway__pb2.StreamIntentsRequest.SerializeToString,
            gateway__pb2.StreamIntentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterDid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intentlayer.v2.GatewayService/RegisterDid',
            gateway__pb2.RegisterDidRequest.SerializeToString,
            gateway__pb2.RegisterDidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamDids(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/intentlayer.v2.GatewayService/StreamDids',
            gateway__pb2.StreamDidsRequest.SerializeToString,
            gateway__pb2.StreamDidsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
