name: Integration Tests

on:
  push:
    branches: [ main, feature/*, hotfix/* ]
  pull_request:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  grpc-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
        
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install --extras grpc
        poetry add grpcio-testing --group dev
        
    - name: Regenerate proto stubs
      run: |
        poetry run python -c "from intentlayer_sdk.gateway._deps import ensure_grpc_installed; ensure_grpc_installed()"
        
    - name: Run gRPC integration tests
      run: |
        poetry run pytest tests/gateway/test_grpc_integration.py -v --cov=intentlayer_sdk.gateway --cov-branch --cov-report=xml
        
    - name: Upload integration test coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: integration

  full-integration:
    runs-on: ubuntu-latest
    needs: grpc-integration
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
        
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install --extras grpc
        
    - name: Run all integration tests
      run: |
        poetry run pytest tests/gateway/ -v --cov=intentlayer_sdk.gateway --cov-branch --cov-report=xml
        
    - name: Upload combined coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: all-integration