name: V1 Protocol Code Check

on:
  push:
    branches: [ main, feature/*, bug/* ]
  pull_request:
    branches: [ main ]

jobs:
  check-v1-code-removal:
    name: Verify V1 Protocol Code Removal
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Check for V1 protocol references
      run: |
        # Define patterns that should not exist in the codebase
        declare -a patterns=(
          "schema_version[[:space:]]*=[[:space:]]*1"
          "schema_version[[:space:]]*==[[:space:]]*1"
          "INTENT_SCHEMA_VERSION[[:space:]]*=[[:space:]]*['\"]?1['\"]?"
          "schema_version[[:space:]]*=[[:space:]]*None"
          "V1[[:space:]]+DidRegistry"
          "V1Protocol"
          "V1[[:space:]]+protocol"
          "v1[[:space:]]+protocol"
          "schema_version:[[:space:]]*None"
          "protocol[[:space:]]*v1"
          "protocol[[:space:]]*=.*v1"
        )
        
        # Excluded paths (tests, changelog, etc.)
        excluded_paths=(
          "-path" "*/.git/*" "-o"
          "-path" "*/.github/*" "-o"
          "-path" "*/\\.venv/*" "-o"
          "-path" "*/CHANGELOG.md" "-o"
          "-path" "*/README.md" "-o"
          "-path" "*/docs/*"
        )
        
        # Check each pattern
        found_v1_code=false
        
        echo "🔍 Checking for deprecated V1 protocol code..."
        
        for pattern in "${patterns[@]}"
        do
          echo "Checking pattern: $pattern"
          # Find files containing the pattern, excluding specific paths
          matches=$(find . -type f \( ${excluded_paths[@]} \) -prune -o -type f -name "*.py" -exec grep -l "$pattern" {} \;)
          
          if [ -n "$matches" ]; then
            echo "⚠️ Found potential V1 protocol code:"
            echo "$matches"
            echo "------------------------"
            for file in $matches; do
              echo "In file: $file"
              grep -n --color=always "$pattern" "$file"
              echo ""
            done
            echo "------------------------"
            found_v1_code=true
          fi
        done
        
        if [ "$found_v1_code" = true ]; then
          echo "❌ V1 protocol code was found. All V1 protocol code should be removed as part of the V1 Protocol Deprecation."
          exit 1
        else
          echo "✅ No V1 protocol code found. All checks passed."
        fi